//
// Created by Olcay Taner YILDIZ on 17.09.2022.
//

#ifndef SPELLCHECKER_OPERATOR_H
#define SPELLCHECKER_OPERATOR_H

#endif //SPELLCHECKER_OPERATOR_H

enum Operator{
    NO_CHANGE,
    MISSPELLED_REPLACE,
    FORCED_MERGE,
    FORCED_SPLIT,
    SPLIT_WITH_SHORTCUT,
    SPELL_CHECK,
    SPLIT,
    FORWARD_MERGE,
    BACKWARD_MERGE
};